In [ ]:
print("Notebook is working")

Notebook is working

In [3]:
import pandas as pd

In [8]:
df=pd.read_csv("retail_cleaned.csv")
df.head()

  customer_name       city  amount order_status
0         Rahul  Hyderabad  1200.0    Delivered
1         Priya  Bengaluru  2500.0    Delivered
2         Rahul  Hyderabad  1800.0      Pending
3         Arjun    Chennai  3200.0    Delivered

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_name  4 non-null      str
 1   city           4 non-null      str
 2   amount         4 non-null      float64
 3   order_status   4 non-null      str
dtypes: float64(1), str(3)
memory usage: 260.0 bytes

In [10]:
df.describe()

            amount
count     4.000000
mean   2175.000000
std     865.544145
min    1200.000000
25%    1650.000000
50%    2150.000000
75%    2675.000000
max    3200.000000

In [11]:
df.isnull().sum()

customer_name    0
city             0
amount           0
order_status     0
dtype: int64

In [13]:
df.groupby("city")["amount"].sum()

city
Bengaluru    2500.0
Chennai      3200.0
Hyderabad    3000.0
Name: amount, dtype: float64

In [14]:
df.groupby("city")["amount"].sum().sort_values(ascending=False)

city
Chennai      3200.0
Hyderabad    3000.0
Bengaluru    2500.0
Name: amount, dtype: float64

In [15]:
df.groupby("order_status")["amount"].sum()

order_status
Delivered    6900.0
Pending      1800.0
Name: amount, dtype: float64

In [17]:
df.groupby("customer_name")["amount"].mean().sort_values(ascending=False)

customer_name
Arjun    3200.0
Priya    2500.0
Rahul    1500.0
Name: amount, dtype: float64